[package]
name = "bevy-craft"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.15"
bevy_compute_noise = "0.4"

tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
crossbeam-channel = "0.5"
encase = "0.10"